"""reestrutura_assinatura_usuario_e_funcionarios

Revision ID: 56ccdade07e1
Revises: 6fbc0c5e0702
Create Date: 2026-04-02 16:46:00.114634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ccdade07e1'
down_revision: Union[str, Sequence[str], None] = '6fbc0c5e0702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('clinica_id', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_admissao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.add_column('assinaturas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('assinaturas_clinica_id_key'), 'assinaturas', type_='unique')
    op.create_unique_constraint(None, 'assinaturas', ['usuario_id'])
    op.drop_constraint(op.f('assinaturas_clinica_id_fkey'), 'assinaturas', type_='foreignkey')
    op.create_foreign_key(None, 'assinaturas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('assinaturas', 'clinica_id')
    op.add_column('clinicas', sa.Column('dono_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clinicas', 'usuarios', ['dono_id'], ['id'])
    op.alter_column('usuarios', 'clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'clinicas', type_='foreignkey')
    op.drop_column('clinicas', 'dono_id')
    op.add_column('assinaturas', sa.Column('clinica_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assinaturas', type_='foreignkey')
    op.create_foreign_key(op.f('assinaturas_clinica_id_fkey'), 'assinaturas', 'clinicas', ['clinica_id'], ['id'])
    op.drop_constraint(None, 'assinaturas', type_='unique')
    op.create_unique_constraint(op.f('assinaturas_clinica_id_key'), 'assinaturas', ['clinica_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('assinaturas', 'usuario_id')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
