"""add_relationship_clinica_assinatura

Revision ID: 6fbc0c5e0702
Revises: 5a4d35501d16
Create Date: 2026-04-02 16:28:56.742311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbc0c5e0702'
down_revision: Union[str, Sequence[str], None] = '5a4d35501d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
