"""fix_ambiguous_fk_relationships

Revision ID: 73dddb5ff1d2
Revises: 56ccdade07e1
Create Date: 2026-04-02 16:47:49.988981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dddb5ff1d2'
down_revision: Union[str, Sequence[str], None] = '56ccdade07e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
