"""reestrutura_assinatura_usuario_e_funcionarios

Revision ID: f8b57e084444
Revises: 73dddb5ff1d2
Create Date: 2026-04-02 16:52:22.728120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b57e084444'
down_revision: Union[str, Sequence[str], None] = '73dddb5ff1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
